server:
  port: 8084
spring:
  application:
    name: seal-zuul
  cloud:
    consul:
      discovery:
        health-check-path: /actuator/health #检测实例健康
        health-check- interval: 10s
        #每隔1es检查
        hostname: localhost
        #配置实例地址
        register: true # 自动注册
        service-name: ${spring.application.name} #实例名称
      host: localhost
      port: 8500
zuul:
  routes:
    real:
      path: /real/**
      service-id: seal-consumer